networks:
  grafana:
  otel-colector:

services:
  loki:
    image: grafana/loki:3.6.2
    restart: always
    ports:
      - "3100:3100"
      # - "9095:9095"
    command: >
      -config.expand-env=true
      -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./.container/loki-data:/loki
    networks:
      - grafana
      - otel-colector

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint: /download-dashboards.sh
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboard-list.txt:/etc/grafana/dashboard-list.txt:ro
      - ./grafana/download-dashboards.sh:/download-dashboards.sh:ro

      - ./.container/grafana-data:/var/lib/grafana
    networks:
      - grafana

  memcached:
    build:
      context: .
      dockerfile: memcached.Dockerfile
    restart: always
    ports:
      - "11211:11211"
    healthcheck:
      test: ["CMD", "/bin/nc", "-z", "memcached", "11211"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4
    networks:
      - otel-colector

  tempo:
    image: grafana/tempo:2.9.0
    restart: always
    depends_on:
      memcached:
        condition: service_healthy
    ports:
      - "14268:14268"
      - "3200:3200"
      # - "9095:9095"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    command: >
      -config.expand-env=true
      -config.file=/etc/tempo/tempo-config.yaml
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo-config.yaml
      - ./tempo-overrides.yaml:/etc/tempo/overrides.yaml
      - ./.container/tempo-data:/var/tempo
    networks:
      - grafana
      - otel-colector
